### ISSUE TITLE
How to use other two models in bns-gcn

### ISSUE THREAD

**Issue by BearBiscuit05** [GATECH-EIC/BNS-GCN#3]
Hello, I have encountered some problems when using bns-gcn, as can be seen from the code you provided, there are three model available for use. But after I modify the script specified by the script, there seems to be an error. I'm not sure where I have to modify if I want to use the other two models.

**Comment by ch-wan** [comment]
Thanks for your question. You can simply specify `--model` as `gcn` or `gat`. Let me know if the problem is not resolved.

**Comment by BearBiscuit05** [comment]
> Thanks for your question. You can simply specify `--model` as `gcn` or `gat`. Let me know if the problem is not resolved.

hi，after directly modifying the model name to gcn, the resulting error is as follows:
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/BNS-GCN/train.py", line 418, in init_processes
    run(g, node_dict, gpb, args)
  File "/root/BNS-GCN/train.py", line 289, in run
    model.cuda()
AttributeError: 'NoneType' object has no attribute 'cuda'
```

**Comment by ch-wan** [comment]
Have you pulled the latest code? GCN was supported last month.

**Comment by BearBiscuit05** [comment]
> Have you pulled the latest code? GCN was supported last month.

I still use the BNS-GCN docker. If I directly `git clone` the latest version of the code in the container, it should be right?

**Comment by ch-wan** [comment]
Yes, it should be right. I think you can also pull the code to the docker environment. I will update the docker soon.

**Comment by BearBiscuit05** [comment]
Hi, I have successfully run multiple algorithms based on your suggestions, but when doing repeated runs of the code, I am running into the following problem and it keeps recurring, I am not sure what is going wrong.
```
  File "/root/miniconda3/envs/DGL/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/DGL/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/BNS-GCN/train.py", line 513, in init_processes
    run(g, node_dict, gpb, args)
  File "/root/miniconda3/envs/DGL/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/BNS-GCN/train.py", line 441, in run
    loss.backward()
  File "/root/miniconda3/envs/DGL/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/DGL/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/BNS-GCN/train.py", line 513, in init_processes
    run(g, node_dict, gpb, args,taskMonitor)
  File "/root/miniconda3/envs/DGL/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/BNS-GCN/train.py", line 441, in run
    loss.backward()
  File "/root/BNS-GCN/helper/feature_buffer.py", line 172, in fn
    self.__grad_transfer(grad)
  File "/root/miniconda3/envs/DGL/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/BNS-GCN/helper/feature_buffer.py", line 178, in __grad_transfer
    self.__gloo_all_to_all(grad, self._grad_cpu, self._b_recv_cpu, None, forward=False)
  File "/root/miniconda3/envs/DGL/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/DGL/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/BNS-GCN/helper/feature_buffer.py", line 172, in fn
    self.__grad_transfer(grad)
  File "/root/BNS-GCN/helper/feature_buffer.py", line 125, in __gloo_all_to_all
    r.wait()
  File "/root/BNS-GCN/helper/feature_buffer.py", line 178, in __grad_transfer
    self.__gloo_all_to_all(grad, self._grad_cpu, self._b_recv_cpu, None, forward=False)
  File "/root/miniconda3/envs/DGL/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
RuntimeError: [/opt/conda/conda-bld/pytorch_1656352465323/work/third_party/gloo/gloo/transport/tcp/pair.cc:589] Read error [172.25.146.180]:27347: Connection reset by peer
  File "/root/BNS-GCN/helper/feature_buffer.py", line 125, in __gloo_all_to_all
    r.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1656352465323/work/third_party/gloo/gloo/transport/tcp/pair.cc:589] Read error [172.25.146.180]:47538: Connection reset by peer
/root/miniconda3/envs/DGL/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 8 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by ch-wan** [comment]
It appears that the program runs out of your system resources. Could you please provide more details about your experiments and environment? Which commands can be launched successfully and which cannot? Thanks.

**Comment by BearBiscuit05** [comment]
Specifically, I conducted the experiment on an idle 4*V100(with 336GB mem) machine on Alibaba Cloud(using ogbn-products dataset). When the code is first run, everything is correct. Then I only modified the model, and the following error was generated. Then I changed the model back to the model that was running successfully before, but this error still occurs.
In addition, I am not sure whether this error is accidental. When I run bns-gcn on the server in our laboratory, this problem will also occur.

**Comment by ch-wan** [comment]
I need more information to reproduce your error. What's the communication backend were you using? What's the command you used for launching the program? Could you please check if the previous runnable programs are completely killed? Sometimes the subprocesses are still alive when you terminate a distributed training script. You can also contact my e-mail so that we can schedule a meeting. Thanks.

**Comment by BearBiscuit05** [comment]
Hi, can you provide an email address, it seems that I did not find it in the repo or paper.

**Comment by ch-wan** [comment]
@BearBiscuit05 Is your problem fixed? When the system resources are constrained (e.g., limited GPU memory, limited disk space), one may observe a similar error because some workers in the training group are killed, and others are waiting for died workers. Again please let me know the detailed environment and the training script you were using. Thanks.

**Comment by ch-wan** [comment]
@BearBiscuit05 It appears that this issue is caused by limited system resources. I'm going to close this issue due to its inactivity. Feel free to reopen it if you have unresolved issues. Thanks!
